import { useEffect, useRef, useState } from 'react';
import { MapPin, Clock, Ticket, ArrowUpRight } from 'lucide-react';
import { NATURE_PICKS, gygHref, GYG_PRICE_AS_OF, localizePicks } from '../shared/gyg/picks';
import { useLang } from '../i18n/useLang';

/**
 * Direct GetYourGuide product deep links — generated by
 * scripts/gyg-rollout.mjs on 2026-07-30. Edit the generator, not this file.
 *
 * The WHOLE card is the link. Every path in shared/gyg/picks.ts was opened in
 * a real browser before shipping; a wrong or delisted GetYourGuide id does not
 * 404, it redirects to a city listing with HTTP 200.
 *
 * Price IS rendered, but never as ours: it is GetYourGuide's own
 * "from" price on GYG_PRICE_AS_OF, printed with the source and that date beside
 * it. Euros — an earlier note in this codebase claimed USD, which was wrong and
 * came from a JSON-LD field the crawler never stored. No "per person" label:
 * the catalogue does not record the unit and some products are priced per group.
 *
 * Ratings and review counts stay out. We cannot keep them current, and a stale
 * "4.6 (869)" is a claim about other people's experience, not a fact.
 */

const COPY = {
  "kicker": {
    "en": "Book now",
    "fi": "Varaa heti",
    "de": "Jetzt buchen",
    "ja": "今すぐ予約",
    "es": "Reserva ya",
    "pt-BR": "Reserve agora",
    "zh-CN": "立即预订",
    "ko": "지금 예약",
    "fr": "Réservez",
    "it": "Prenoti ora",
    "nl": "Boek nu",
    "sv": "Boka nu"
  },
  "ctaProduct": {
    "en": "Check availability",
    "fi": "Katso saatavuus",
    "de": "Verfügbarkeit prüfen",
    "ja": "空き状況を見る",
    "es": "Ver disponibilidad",
    "pt-BR": "Ver disponibilidade",
    "zh-CN": "查看可订日期",
    "ko": "예약 가능 여부 확인",
    "fr": "Voir les disponibilités",
    "it": "Vedi disponibilità",
    "nl": "Bekijk beschikbaarheid",
    "sv": "Se tillgänglighet"
  },
  "ctaCategory": {
    "en": "Browse all",
    "fi": "Selaa kaikki",
    "de": "Alle ansehen",
    "ja": "すべて見る",
    "es": "Ver todo",
    "pt-BR": "Ver tudo",
    "zh-CN": "查看全部",
    "ko": "전체 보기",
    "fr": "Voir tout",
    "it": "Vedi tutto",
    "nl": "Bekijk alles",
    "sv": "Se alla"
  },
  "via": {
    "en": "via GetYourGuide",
    "fi": "GetYourGuiden kautta",
    "de": "über GetYourGuide",
    "ja": "GetYourGuide 経由",
    "es": "con GetYourGuide",
    "pt-BR": "via GetYourGuide",
    "zh-CN": "通过 GetYourGuide",
    "ko": "GetYourGuide 제공",
    "fr": "via GetYourGuide",
    "it": "tramite GetYourGuide",
    "nl": "via GetYourGuide",
    "sv": "via GetYourGuide"
  },
  "priceFrom": {
    "en": "from",
    "fi": "alkaen",
    "de": "ab",
    "ja": "〜より",
    "es": "desde",
    "pt-BR": "a partir de",
    "zh-CN": "起价",
    "ko": "부터",
    "fr": "à partir de",
    "it": "da",
    "nl": "vanaf",
    "sv": "från"
  },
  "priceSource": {
    "en": "Price on GetYourGuide",
    "fi": "Hinta GetYourGuidessa",
    "de": "Preis auf GetYourGuide",
    "ja": "GetYourGuide の価格",
    "es": "Precio en GetYourGuide",
    "pt-BR": "Preço no GetYourGuide",
    "zh-CN": "GetYourGuide 价格",
    "ko": "GetYourGuide 가격",
    "fr": "Prix sur GetYourGuide",
    "it": "Prezzo su GetYourGuide",
    "nl": "Prijs op GetYourGuide",
    "sv": "Pris på GetYourGuide"
  },
  "headingProduct": {
    "en": "Bookable today",
    "fi": "Varattavissa tänään",
    "de": "Heute buchbar",
    "ja": "今日予約できる体験",
    "es": "Reservable hoy",
    "pt-BR": "Reservável hoje",
    "zh-CN": "今天即可预订",
    "ko": "오늘 예약 가능",
    "fr": "Réservable aujourd’hui",
    "it": "Prenotabile oggi",
    "nl": "Vandaag te boeken",
    "sv": "Bokningsbart i dag"
  },
  "ledeProduct": {
    "en": "Hand-picked nature tours, bookable online through GetYourGuide.",
    "fi": "Poimitut luontoretket, varattavissa verkossa GetYourGuiden kautta.",
    "de": "Ausgewählte Naturtouren, online über GetYourGuide buchbar.",
    "ja": "厳選したネイチャーツアー。GetYourGuide でオンライン予約できます。",
    "es": "Excursiones de naturaleza seleccionadas, reservables en línea con GetYourGuide.",
    "pt-BR": "Passeios na natureza selecionados, reserváveis online via GetYourGuide.",
    "zh-CN": "精选自然生态行程，可通过 GetYourGuide 在线预订。",
    "ko": "엄선한 자연 투어, GetYourGuide에서 온라인 예약.",
    "fr": "Une sélection de sorties nature, réservables en ligne via GetYourGuide.",
    "it": "Escursioni nella natura selezionate, prenotabili online tramite GetYourGuide.",
    "nl": "Geselecteerde natuurtochten, online te boeken via GetYourGuide.",
    "sv": "Utvalda naturturer, bokas online via GetYourGuide."
  },
  "headingCategory": {
    "en": "Browse and book on GetYourGuide",
    "fi": "Selaa ja varaa GetYourGuidessa",
    "de": "Auf GetYourGuide stöbern und buchen",
    "ja": "GetYourGuide で探して予約",
    "es": "Explora y reserva en GetYourGuide",
    "pt-BR": "Explore e reserve no GetYourGuide",
    "zh-CN": "在 GetYourGuide 浏览并预订",
    "ko": "GetYourGuide에서 둘러보고 예약",
    "fr": "Parcourez et réservez sur GetYourGuide",
    "it": "Sfogli e prenoti su GetYourGuide",
    "nl": "Bekijk en boek op GetYourGuide",
    "sv": "Bläddra och boka på GetYourGuide"
  },
  "ledeCategory": {
    "en": "A partner-maintained list, always current. We do not name a single tour here.",
    "fi": "Kumppanin ylläpitämä lista, aina ajantasainen; emme nimeä yksittäistä retkeä.",
    "de": "Eine vom Partner gepflegte Liste, immer aktuell.",
    "ja": "パートナーが管理する最新のリストです。",
    "es": "Una lista mantenida por el socio, siempre actualizada.",
    "pt-BR": "Uma lista mantida pelo parceiro, sempre atual.",
    "zh-CN": "由合作伙伴维护的列表，始终保持最新。",
    "ko": "파트너가 관리하는 항상 최신 목록입니다.",
    "fr": "Une liste tenue à jour par le partenaire.",
    "it": "Un elenco aggiornato dal partner.",
    "nl": "Een door de partner bijgehouden, actuele lijst.",
    "sv": "En lista som partnern håller uppdaterad."
  }
};

/**
 * The as-of date next to each price, in the page's locale. Not "today" —
 * the day the price was actually read off GetYourGuide, which is the only date
 * we can stand behind.
 */
const fiDate = (iso: string, locale: string): string => {
  const d = new Date(iso + 'T00:00:00Z');
  // timeZone UTC because the stamp is a plain date: without it a reader west of
  // UTC is shown the previous day. Locale is the page's, never the browser's.
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleDateString(locale, { day: 'numeric', month: 'numeric', year: 'numeric', timeZone: 'UTC' });
};

/**
 * GetYourGuide's own "activities" widget shows these products with GetYourGuide's
 * product photos and live prices. A partner's product is never shown with an
 * illustration of our own, and the affiliate programme gives us links, not
 * pictures, so the photos come only through the widget. The Integration Analyzer
 * script in index.html turns the data-gyg-* box into an iframe (same mechanism as
 * laplandtours, laplanddeals and laplandkids).
 *
 * If no iframe has mounted after a few seconds (ad blocker, tracking protection,
 * slow network) the box collapses and the same products are listed as plain text
 * cards routed through the Worker, so the section is never an empty rectangle.
 * A late iframe still takes over: the check keeps polling.
 */
const GYG_PARTNER_ID = 'VRMKD7N';
const GYG_LOCALE: Record<string, string> = {
  en: 'en-US', fi: 'fi-FI', de: 'de-DE', ja: 'ja-JP', es: 'es-ES',
  'pt-BR': 'pt-BR', 'zh-CN': 'zh-CN', ko: 'ko-KR', fr: 'fr-FR', it: 'it-IT', nl: 'nl-NL', sv: 'sv-SE',
};
/** Product id from the path's "-t<id>" suffix. */
const tourId = (path: string): string | null => /-t(\d+)\/?$/.exec(path)?.[1] ?? null;

export default function GygPicks() {
  const lang = useLang();
  const t = (m: Record<string, string>): string => m[lang] ?? m.en;
  const L = COPY;
  // Title, place and duration in the page's language (2026-09-26). A row with no
  // translation for this locale is dropped rather than shown in English.
  const rows = localizePicks(NATURE_PICKS, lang);
  const ids = rows.map((p) => tourId(p.path)).filter((x): x is string => !!x).join(',');

  const boxRef = useRef<HTMLDivElement>(null);
  const [blocked, setBlocked] = useState(false);
  useEffect(() => {
    // State is only set inside the timers (react-hooks/set-state-in-effect);
    // the first tick re-evaluates after a language switch too.
    let cancelled = false;
    let waited = 0;
    const FIRST = 2500, STEP = 1000, MAX = 12000;
    let timer: ReturnType<typeof setTimeout>;
    const tick = (delay: number) => {
      timer = setTimeout(() => {
        if (cancelled) return;
        waited += delay;
        if (boxRef.current?.querySelector('iframe')) { setBlocked(false); return; }
        setBlocked(true);
        if (waited < MAX) tick(STEP);
      }, delay);
    };
    tick(FIRST);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [lang, ids]);

  if (!rows.length) return null;

  return (
    <section className="py-16 sm:py-20 px-4 sm:px-6 bg-transparent">
      <div className="max-w-7xl mx-auto">
        <div className="mb-10 sm:mb-12">
          <p className="font-bold tracking-[0.18em] uppercase text-sm mb-3 text-[#BE185D]">{t(L.kicker)}</p>
          <h2 className="text-3xl sm:text-4xl md:text-5xl font-bold mb-3 text-[#0F172A]">
            {t(L.headingProduct)}
          </h2>
          <p className="max-w-2xl text-black/65">{t(L.ledeProduct)}</p>
        </div>

        {/* The widget picks its own columns from its width: one (about 1 500 px of
            stacked cards on a phone), three plus a lone fourth on a tablet, four
            from about 1 100 px. Below xl the box is therefore given a fixed
            four-across width and the row scrolls sideways, with the next card
            peeking in at the edge; from xl the column is wide enough. */}
        <div className={blocked ? '' : '-mx-4 px-4 sm:-mx-6 sm:px-6 overflow-x-auto overscroll-x-contain xl:mx-0 xl:px-0 xl:overflow-visible'}>
          <div
            ref={boxRef}
            key={`gyg-${lang}-${ids}`}
            className={blocked ? 'h-0 overflow-hidden' : 'min-h-[160px] w-[1120px] xl:w-auto'}
            data-gyg-widget="activities"
            data-gyg-partner-id={GYG_PARTNER_ID}
            data-gyg-locale-code={GYG_LOCALE[lang] ?? 'en-US'}
            data-gyg-cmp="lv_laplandnature_home"
            data-gyg-tour-ids={ids}
            data-gyg-number-of-items={String(rows.length)}
          />
        </div>

        {blocked && (
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">
        {rows.map((p) => (
          <a
            key={p.path}
            href={gygHref(p, lang)}
            target="_blank"
            rel="sponsored nofollow noopener"
            className="group flex flex-row items-center gap-3 p-4 sm:flex-col sm:items-stretch sm:gap-0 sm:p-0 overflow-hidden rounded-2xl border bg-white border-black/10 shadow-sm no-underline transition-all duration-300 hover:-translate-y-1 hover:shadow-xl hover:border-[#BE185D]/40"
          >
            <div className="flex min-w-0 flex-1 flex-col sm:p-5">
              <p className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-[#BE185D]">
                <MapPin className="h-3.5 w-3.5" aria-hidden="true" />
                {p.place}
              </p>

              <h3 className="mt-0.5 sm:mt-2 sm:flex-1 text-[15px] sm:text-base font-bold leading-snug text-[#0F172A]">{p.title}</h3>

              {/* Only when a real length exists — one source row carried a sales
                  badge in this field, and a badge is not a duration. */}
              {p.duration && (
                <p className="mt-1 sm:mt-2 inline-flex items-center gap-1.5 text-sm text-black/55">
                  <Clock className="h-3.5 w-3.5" aria-hidden="true" />
                  {p.duration}
                </p>
              )}

              {/* GetYourGuide's OWN "from" price, with source and date beside it.
                  It is not our price and we cannot keep it current — the partner
                  changes it. Rendering it bare would be a promise we break on
                  their behalf; rendering it dated is a fact about a moment.
                  Deliberately no "per person": spot checks showed per-person on
                  the rows we opened, but the catalogue does not record the unit
                  and some GetYourGuide products are priced per group. */}
              {p.price && (
                <p className="mt-1 sm:mt-3 flex items-baseline gap-1.5">
                  <span className="text-[11px] uppercase tracking-wider text-black/55">{t(L.priceFrom)}</span>
                  <span className="text-lg font-bold text-[#0F172A]">{p.price}</span>
                </p>
              )}

              <span className="mt-4 hidden sm:inline-flex items-center justify-center gap-2 rounded-full bg-[#DB2777] px-4 py-2.5 text-sm font-bold text-white transition-opacity group-hover:opacity-90">
                <Ticket className="h-4 w-4" aria-hidden="true" />
                {t(L.ctaProduct)}
                <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true" />
              </span>

              <span className="mt-1 sm:mt-2 text-left sm:text-center text-[11px] text-black/55">
                {p.price ? `${t(L.priceSource)} ${fiDate(GYG_PRICE_AS_OF, lang)}` : t(L.via)}
              </span>
            </div>
            {/* On a phone the row has no button; the arrow says it opens GetYourGuide. */}
            <ArrowUpRight className="h-5 w-5 shrink-0 self-center text-[#BE185D] sm:hidden" aria-hidden="true" />
          </a>
        ))}
        </div>
        )}
      </div>
    </section>
  );
}
