import { useEffect, useRef, useState } from 'react';
import type { CSSProperties } from 'react';
import { MapPin, Clock, Ticket, ArrowUpRight, Footprints, MountainSnow, Snowflake, Sparkles, TreePine } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { NATURE_PICKS, gygHref, GYG_PRICE_AS_OF, localizePicks } from '../shared/gyg/picks';
import { useLang } from '../i18n/useLang';

/**
 * Direct GetYourGuide product deep links — generated by
 * scripts/gyg-rollout.mjs on 2026-07-30. Edit the generator, not this file.
 *
 * The WHOLE card is the link. Every path in shared/gyg/picks.ts was opened in
 * a real browser before shipping; a wrong or delisted GetYourGuide id does not
 * 404, it redirects to a city listing with HTTP 200.
 *
 * Price IS rendered, but never as ours: it is GetYourGuide's own
 * "from" price on GYG_PRICE_AS_OF, printed with the source and that date beside
 * it. Euros — an earlier note in this codebase claimed USD, which was wrong and
 * came from a JSON-LD field the crawler never stored. No "per person" label:
 * the catalogue does not record the unit and some products are priced per group.
 *
 * Ratings and review counts stay out. We cannot keep them current, and a stale
 * "4.6 (869)" is a claim about other people's experience, not a fact.
 */

const COPY = {
  "kicker": {
    "en": "Book now",
    "fi": "Varaa heti",
    "de": "Jetzt buchen",
    "ja": "今すぐ予約",
    "es": "Reserva ya",
    "pt-BR": "Reserve agora",
    "zh-CN": "立即预订",
    "ko": "지금 예약",
    "fr": "Réservez",
    "it": "Prenoti ora",
    "nl": "Boek nu",
    "sv": "Boka nu"
  },
  "ctaProduct": {
    "en": "Check availability",
    "fi": "Katso saatavuus",
    "de": "Verfügbarkeit prüfen",
    "ja": "空き状況を見る",
    "es": "Ver disponibilidad",
    "pt-BR": "Ver disponibilidade",
    "zh-CN": "查看可订日期",
    "ko": "예약 가능 여부 확인",
    "fr": "Voir les disponibilités",
    "it": "Vedi disponibilità",
    "nl": "Bekijk beschikbaarheid",
    "sv": "Se tillgänglighet"
  },
  "ctaCategory": {
    "en": "Browse all",
    "fi": "Selaa kaikki",
    "de": "Alle ansehen",
    "ja": "すべて見る",
    "es": "Ver todo",
    "pt-BR": "Ver tudo",
    "zh-CN": "查看全部",
    "ko": "전체 보기",
    "fr": "Voir tout",
    "it": "Vedi tutto",
    "nl": "Bekijk alles",
    "sv": "Se alla"
  },
  "via": {
    "en": "via GetYourGuide",
    "fi": "GetYourGuiden kautta",
    "de": "über GetYourGuide",
    "ja": "GetYourGuide 経由",
    "es": "con GetYourGuide",
    "pt-BR": "via GetYourGuide",
    "zh-CN": "通过 GetYourGuide",
    "ko": "GetYourGuide 제공",
    "fr": "via GetYourGuide",
    "it": "tramite GetYourGuide",
    "nl": "via GetYourGuide",
    "sv": "via GetYourGuide"
  },
  "priceFrom": {
    "en": "from",
    "fi": "alkaen",
    "de": "ab",
    "ja": "〜より",
    "es": "desde",
    "pt-BR": "a partir de",
    "zh-CN": "起价",
    "ko": "부터",
    "fr": "à partir de",
    "it": "da",
    "nl": "vanaf",
    "sv": "från"
  },
  "priceSource": {
    "en": "Price on GetYourGuide",
    "fi": "Hinta GetYourGuidessa",
    "de": "Preis auf GetYourGuide",
    "ja": "GetYourGuide の価格",
    "es": "Precio en GetYourGuide",
    "pt-BR": "Preço no GetYourGuide",
    "zh-CN": "GetYourGuide 价格",
    "ko": "GetYourGuide 가격",
    "fr": "Prix sur GetYourGuide",
    "it": "Prezzo su GetYourGuide",
    "nl": "Prijs op GetYourGuide",
    "sv": "Pris på GetYourGuide"
  },
  "headingProduct": {
    "en": "Bookable today",
    "fi": "Varattavissa tänään",
    "de": "Heute buchbar",
    "ja": "今日予約できる体験",
    "es": "Reservable hoy",
    "pt-BR": "Reservável hoje",
    "zh-CN": "今天即可预订",
    "ko": "오늘 예약 가능",
    "fr": "Réservable aujourd’hui",
    "it": "Prenotabile oggi",
    "nl": "Vandaag te boeken",
    "sv": "Bokningsbart i dag"
  },
  "ledeProduct": {
    "en": "Hand-picked nature tours, bookable online through GetYourGuide.",
    "fi": "Poimitut luontoretket, varattavissa verkossa GetYourGuiden kautta.",
    "de": "Ausgewählte Naturtouren, online über GetYourGuide buchbar.",
    "ja": "厳選したネイチャーツアー。GetYourGuide でオンライン予約できます。",
    "es": "Excursiones de naturaleza seleccionadas, reservables en línea con GetYourGuide.",
    "pt-BR": "Passeios na natureza selecionados, reserváveis online via GetYourGuide.",
    "zh-CN": "精选自然生态行程，可通过 GetYourGuide 在线预订。",
    "ko": "엄선한 자연 투어, GetYourGuide에서 온라인 예약.",
    "fr": "Une sélection de sorties nature, réservables en ligne via GetYourGuide.",
    "it": "Escursioni nella natura selezionate, prenotabili online tramite GetYourGuide.",
    "nl": "Geselecteerde natuurtochten, online te boeken via GetYourGuide.",
    "sv": "Utvalda naturturer, bokas online via GetYourGuide."
  },
  "headingCategory": {
    "en": "Browse and book on GetYourGuide",
    "fi": "Selaa ja varaa GetYourGuidessa",
    "de": "Auf GetYourGuide stöbern und buchen",
    "ja": "GetYourGuide で探して予約",
    "es": "Explora y reserva en GetYourGuide",
    "pt-BR": "Explore e reserve no GetYourGuide",
    "zh-CN": "在 GetYourGuide 浏览并预订",
    "ko": "GetYourGuide에서 둘러보고 예약",
    "fr": "Parcourez et réservez sur GetYourGuide",
    "it": "Sfogli e prenoti su GetYourGuide",
    "nl": "Bekijk en boek op GetYourGuide",
    "sv": "Bläddra och boka på GetYourGuide"
  },
  "ledeCategory": {
    "en": "A partner-maintained list, always current. We do not name a single tour here.",
    "fi": "Kumppanin ylläpitämä lista, aina ajantasainen; emme nimeä yksittäistä retkeä.",
    "de": "Eine vom Partner gepflegte Liste, immer aktuell.",
    "ja": "パートナーが管理する最新のリストです。",
    "es": "Una lista mantenida por el socio, siempre actualizada.",
    "pt-BR": "Uma lista mantida pelo parceiro, sempre atual.",
    "zh-CN": "由合作伙伴维护的列表，始终保持最新。",
    "ko": "파트너가 관리하는 항상 최신 목록입니다.",
    "fr": "Une liste tenue à jour par le partenaire.",
    "it": "Un elenco aggiornato dal partner.",
    "nl": "Een door de partner bijgehouden, actuele lijst.",
    "sv": "En lista som partnern håller uppdaterad."
  }
};

/**
 * The as-of date next to each price, in the page's locale. Not "today" —
 * the day the price was actually read off GetYourGuide, which is the only date
 * we can stand behind.
 */
const fiDate = (iso: string, locale: string): string => {
  const d = new Date(iso + 'T00:00:00Z');
  // timeZone UTC because the stamp is a plain date: without it a reader west of
  // UTC is shown the previous day. Locale is the page's, never the browser's.
  return Number.isNaN(d.getTime())
    ? iso
    : d.toLocaleDateString(locale, { day: 'numeric', month: 'numeric', year: 'numeric', timeZone: 'UTC' });
};

/**
 * GetYourGuide's own "activities" widget shows these products with GetYourGuide's
 * product photos and live prices. A partner's product is never shown with an
 * illustration of our own, and the affiliate programme gives us links, not
 * pictures, so the photos come only through the widget. The Integration Analyzer
 * script in index.html turns the data-gyg-* box into an iframe (same mechanism as
 * laplandtours, laplanddeals and laplandkids).
 *
 * If no iframe has mounted after a few seconds (ad blocker, tracking protection,
 * slow network) the box collapses and the same products are listed as plain text
 * cards routed through the Worker, so the section is never an empty rectangle.
 * A late iframe still takes over: the check keeps polling.
 */
const GYG_PARTNER_ID = 'VRMKD7N';
const GYG_LOCALE: Record<string, string> = {
  en: 'en-US', fi: 'fi-FI', de: 'de-DE', ja: 'ja-JP', es: 'es-ES',
  'pt-BR': 'pt-BR', 'zh-CN': 'zh-CN', ko: 'ko-KR', fr: 'fr-FR', it: 'it-IT', nl: 'nl-NL', sv: 'sv-SE',
};
/** Product id from the path's "-t<id>" suffix. */
const tourId = (path: string): string | null => /-t(\d+)\/?$/.exec(path)?.[1] ?? null;

/**
 * The fallback cards carry no picture (4.10.2026, Vesa looked at them with the
 * widget blocked: "miksi visuaalisuus on näin poor?"). A photo is not allowed
 * here: a partner's product is never AI, and a scenery photo on a product card
 * reads as a photo OF the product. So the card gets the network's placeholder
 * gradient with contour lines, an icon for the kind of trip and the place in
 * Bebas — a sign of what the trip is, not a picture claiming to show it.
 * Keyed on the product path (English slug, same in every language — `title` is
 * already localised by localizePicks); order matters (a "hiking and
 * snowshoeing" trip is hiking first).
 */
const ICON_RULES: Array<[RegExp, LucideIcon]> = [
  [/aurora|northern-lights/i, Sparkles],
  [/waterfall|canyon/i, MountainSnow],
  [/hiking/i, Footprints],
  [/snowshoe|snowhotel/i, Snowflake],
];
const tripIcon = (path: string): LucideIcon =>
  ICON_RULES.find(([re]) => re.test(path))?.[1] ?? TreePine;

/** Network placeholder gradient (CLAUDE.md) + faint contour rings. */
const HEADER_BG: CSSProperties = {
  backgroundImage: [
    'repeating-radial-gradient(circle at 85% 115%, rgba(255,255,255,0.07) 0 1px, transparent 1px 15px)',
    'radial-gradient(120% 90% at 0% 0%, rgba(16,185,129,0.28), transparent 60%)',
    'linear-gradient(135deg, #0d2818 0%, #0F172A 55%, #1e1b4b 100%)',
  ].join(','),
};

export default function GygPicks() {
  const lang = useLang();
  const t = (m: Record<string, string>): string => m[lang] ?? m.en;
  const L = COPY;
  // Title, place and duration in the page's language (2026-09-26). A row with no
  // translation for this locale is dropped rather than shown in English.
  const rows = localizePicks(NATURE_PICKS, lang);
  const ids = rows.map((p) => tourId(p.path)).filter((x): x is string => !!x).join(',');

  const boxRef = useRef<HTMLDivElement>(null);
  const [blocked, setBlocked] = useState(false);
  useEffect(() => {
    // State is only set inside the timers (react-hooks/set-state-in-effect);
    // the first tick re-evaluates after a language switch too.
    let cancelled = false;
    let waited = 0;
    const FIRST = 2500, STEP = 1000, MAX = 12000;
    let timer: ReturnType<typeof setTimeout>;
    const tick = (delay: number) => {
      timer = setTimeout(() => {
        if (cancelled) return;
        waited += delay;
        if (boxRef.current?.querySelector('iframe')) { setBlocked(false); return; }
        setBlocked(true);
        if (waited < MAX) tick(STEP);
      }, delay);
    };
    tick(FIRST);
    return () => { cancelled = true; clearTimeout(timer); };
  }, [lang, ids]);

  if (!rows.length) return null;

  return (
    <section className="py-16 sm:py-20 px-4 sm:px-6 bg-transparent">
      <div className="max-w-7xl mx-auto">
        <div className="mb-10 sm:mb-12">
          <p className="font-bold tracking-[0.18em] uppercase text-sm mb-3 text-[#BE185D]">{t(L.kicker)}</p>
          <h2 className="font-heading text-4xl sm:text-5xl md:text-6xl tracking-wider mb-3 text-[#0F172A]">
            {t(L.headingProduct)}
          </h2>
          <p className="max-w-2xl text-black/65">{t(L.ledeProduct)}</p>
        </div>

        {/* The widget picks its own columns from its width: one (about 1 500 px of
            stacked cards on a phone), three plus a lone fourth on a tablet, four
            from about 1 100 px. Below xl the box is therefore given a fixed
            four-across width and the row scrolls sideways, with the next card
            peeking in at the edge; from xl the column is wide enough. */}
        <div className={blocked ? '' : '-mx-4 px-4 sm:-mx-6 sm:px-6 overflow-x-auto overscroll-x-contain xl:mx-0 xl:px-0 xl:overflow-visible'}>
          <div
            ref={boxRef}
            key={`gyg-${lang}-${ids}`}
            className={blocked ? 'h-0 overflow-hidden' : 'min-h-[160px] w-[1120px] xl:w-auto'}
            data-gyg-widget="activities"
            data-gyg-partner-id={GYG_PARTNER_ID}
            data-gyg-locale-code={GYG_LOCALE[lang] ?? 'en-US'}
            data-gyg-cmp="lv_laplandnature_home"
            data-gyg-tour-ids={ids}
            data-gyg-number-of-items={String(rows.length)}
          />
        </div>

        {blocked && (
        <div className="grid gap-4 sm:gap-5 sm:grid-cols-2 xl:grid-cols-4">
        {rows.map((p) => {
          const Icon = tripIcon(p.path);
          return (
          <a
            key={p.path}
            href={gygHref(p, lang)}
            target="_blank"
            rel="sponsored nofollow noopener"
            className="group flex flex-row items-stretch overflow-hidden rounded-2xl border bg-white border-black/10 shadow-[0_18px_40px_-28px_rgba(15,23,42,0.55)] no-underline transition-[transform,box-shadow,border-color] duration-300 ease-out hover:-translate-y-1 hover:shadow-[0_28px_56px_-28px_rgba(15,23,42,0.6)] hover:border-[#BE185D]/40 sm:flex-col"
          >
            {/* Sign of the trip, not a picture of it (see ICON_RULES). On a phone a
                square tile beside the text, from sm a header band with the place. */}
            <div
              aria-hidden="true"
              className="relative flex w-20 shrink-0 items-center justify-center sm:h-36 sm:w-auto sm:items-start sm:justify-between sm:p-5"
              style={HEADER_BG}
            >
              <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10 ring-1 ring-inset ring-white/20 text-[#6EE7B7] transition-transform duration-300 ease-out group-hover:scale-105">
                <Icon className="h-6 w-6" strokeWidth={1.75} />
              </span>
              <span className="absolute bottom-3 left-5 hidden font-heading text-3xl leading-none tracking-wide text-snow sm:block">
                {p.place}
              </span>
            </div>

            <div className="flex min-w-0 flex-1 flex-col p-4 sm:p-5">
              <p className="inline-flex items-center gap-1.5 text-xs font-bold uppercase tracking-wider text-[#BE185D] sm:hidden">
                <MapPin className="h-3.5 w-3.5" aria-hidden="true" />
                {p.place}
              </p>

              {/* DM Sans, not the global Bebas h3: condensed capitals at 16-17 px
                  were the unreadable part of the old card. */}
              <h3 className="mt-1 sm:mt-0 sm:flex-1 font-body normal-case tracking-normal text-[16px] sm:text-[17px] font-bold leading-snug text-[#0F172A] [&:lang(ja)]:[word-break:auto-phrase] [&:lang(ko)]:[word-break:keep-all]">
                {p.title}
              </h3>

              {/* Duration only when a real length exists — one source row carried a
                  sales badge in this field, and a badge is not a duration.
                  GetYourGuide's OWN "from" price, never ours, with source and date
                  under the button. No "per person": the catalogue does not record
                  the unit and some products are priced per group. */}
              {(p.duration || p.price) && (
                <div className="mt-2 sm:mt-4 flex flex-wrap items-center gap-x-3 gap-y-1">
                  {p.duration && (
                    <span className="inline-flex items-center gap-1.5 text-sm text-black/60">
                      <Clock className="h-4 w-4" aria-hidden="true" />
                      {p.duration}
                    </span>
                  )}
                  {p.price && (
                    <span className="inline-flex items-baseline gap-1.5 sm:ml-auto">
                      <span className="text-xs text-black/60">{t(L.priceFrom)}</span>
                      <span className="font-heading text-2xl sm:text-3xl leading-none tracking-wide text-[#0F172A]">{p.price}</span>
                    </span>
                  )}
                </div>
              )}

              <span className="mt-4 hidden sm:inline-flex items-center justify-center gap-2 rounded-full bg-[#DB2777] px-4 py-2.5 text-sm font-bold text-white transition-colors group-hover:bg-[#BE185D]">
                <Ticket className="h-4 w-4" aria-hidden="true" />
                {t(L.ctaProduct)}
                <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true" />
              </span>

              <span className="mt-1.5 sm:mt-2 text-left sm:text-center text-xs text-black/60">
                {p.price ? `${t(L.priceSource)} ${fiDate(GYG_PRICE_AS_OF, lang)}` : t(L.via)}
              </span>
            </div>
            {/* On a phone the row has no button; the arrow says it opens GetYourGuide. */}
            <ArrowUpRight className="mr-3 h-5 w-5 shrink-0 self-center text-[#BE185D] sm:hidden" aria-hidden="true" />
          </a>
          );
        })}
        </div>
        )}
      </div>
    </section>
  );
}
