// Generated by scripts/gyg-wire-images.mjs — do not edit by hand.
//
// Card images for the GetYourGuide picks, keyed by the product path so a card
// and its image can never drift apart. AI-generated with Picsart (gpt-image-2)
// on 2026-07-30; GetYourGuide's own photos are NOT used, they belong to the
// operators. One image is used on exactly one ecosystem site.
import img0 from '../assets/gyg/hiking-and-snowshoeing-adventure-in-lapland.webp';
import img1 from '../assets/gyg/frozen-waterfalls-of-korouoma-canyon-pro-photo.webp';
import img2 from '../assets/gyg/private-pallas-yll-stunturi-national-park-snow.webp';
import img3 from '../assets/gyg/snowshoeing-tour-in-urho-kekkonen-national-par.webp';

export const GYG_IMAGES: Record<string, string> = {
  'rovaniemi-l2653/rovaniemi-hiking-and-snowshoeing-adventure-in-lapland-t183797': img0,
  'rovaniemi-l2653/rovaniemi-frozen-waterfalls-of-korouoma-winter-adventure-t462678': img1,
  'sirkka-l139331/snowshoeing-in-the-national-park-t449218': img2,
  'saariselka-l181615/saariselka-snowshoeing-tour-in-urho-kekkonen-national-park-t800450': img3,
};
